language: go
go:
- '1.0'
- '1.11'
before_install:
- openssl aes-256-cbc -K $encrypted_d9477acaa3a0_key -iv $encrypted_d9477acaa3a0_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d

deploy:
  provider: gae
  keyfile: "client-secret.json"
  project: "remote-job-salary-calculator"
