name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...
    
    # - name: Test
    #  run: go test -v ./...
      
    - name: Google App Engine (GAE) Deploy
      # You may pin to the exact commit or the version.
      # uses: atRobertoFlores/gae_deploy_action@b1ff9efc841e7415ba3510bf94b23c8fb46197eb
      uses: atRobertoFlores/gae_deploy_action@1.2
      with:
        # Service Account JSON key
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
        # GAE project name
        project_name: ${{ secrets.PROJECT_NAME }}
